/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qa;

import org.junit.Test;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;

import java.util.function.BiFunction;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();

    }

    @Test
    public void testLambda() {
        BiFunction<Integer, Integer, Integer> func = (a, b) -> {
            return a + b;
        };

        assertThat(func.apply(4, 2), is(6));
    }

    @Test
    public void testNd4jConcat() {
        INDArray array0 = Nd4j.create(new int[] { 5, 8 });
        INDArray array1 = Nd4j.create(new int[] { 2, 4 });
        array0.

                assertThat(Nd4j.concat(1, array0, array1), is(Nd4j.create(new int[][] { { 5, 8 }, { 2, 4 } })));
    }
}
