/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qa;

import org.junit.Test;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.NDArrayIndex;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;

import java.util.function.BiFunction;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();

    }

    @Test
    public void testLambda() {
        BiFunction<Integer, Integer, Integer> func = (a, b) -> {
            return a + b;
        };

        assertThat(func.apply(4, 2), is(6));
    }

    @Test
    public void testINDArrayGet() {
        INDArray array = Nd4j.create(new double[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 });

        assertThat(array.get(NDArrayIndex.indices(1, 3, 5)), is(Nd4j.create(new double[] { 1, 3, 5 })));
    }

    @Test
    public void testINDArraySum() {
        INDArray array = Nd4j.create(new double[] { -2.0, 4, 8 });

        assertThat(array.sumNumber().doubleValue(), is(10.0));
    }
}
