/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quantum_annealing_simulation;

import java.util.Random;

import org.la4j.Matrix;
import org.la4j.Vector;

public class App {
    public static void main(String[] args) {
        final int N = 5;

        Vector E = Vector.zero((int) Math.pow(2, N));
        Random rand = new Random();
        for (int i = 0; i < E.length(); i++) {
            // Gen gaussian
            E.set(i, rand.nextGaussian());
        }

        QuantumAnnealing quantumAnnealing = new QuantumAnnealing(N, E);

        Matrix H = null;
        double step = 0.01;
        Vector time_steps = Vector.zero((int) (quantumAnnealing.getTau() / step) + 1);
        for (int i = 0; i < time_steps.length(); i++) {
            time_steps.set(i, step * i);
        }

        for (Double t : time_steps) {
            H = quantumAnnealing.create_tfim(t, H);
        }
    }
}