/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quantum_annealing_simulation;

public class App {
    public static void main(String[] args) {
        final int N = 5;
        double E[] = new double[(int) Math.pow(2, N)];
    }
}
